### ISSUE TITLE
Use different package.json matching

### ISSUE THREAD

**Issue by mlewand** [mlewand/ckeditor5-keyboard-marker#4]
https://github.com/mlewand/ckeditor5-keyboard-marker/blob/c3044f40c6d92a53769971176cc105a02246d05f/package.json#L11-L13

Current `^` matchers might cause duplicate modules problem. Instead we should use `>=` like \`">=20.0.0" or something.

**Comment by fredck** [comment]
Let me expand this change a bit... additionally, these should be "peerDependencies". In this way, we're sure that we're depending on the version that the "build" is using and don't eventually mislead npm/yarn to install old versions.
