### ISSUE TITLE
The package released on npm is broken. Icon missing

### ISSUE THREAD

**Issue by fredck** [mlewand/ckeditor5-keyboard-marker#6]
I've now switched to use the npm release of the package since v1.0.2 (thanks for that!) buuuuuttt.... it is broken.

The reason:

*   [The "icons" directory is not included when publishing](https://github.com/mlewand/ckeditor5-keyboard-marker/blob/e791bc06ca33029e69261413bf4bdc8e4dc069a0/package.json#L35-L37).
*   [The "icons" directory is required](https://github.com/mlewand/ckeditor5-keyboard-marker/blob/e791bc06ca33029e69261413bf4bdc8e4dc069a0/src/KbdUI.js#L5).

It's a one-line fix in package.json... and hopefully we'll see v1.0.3 soon ;)

**Comment by fredck** [comment]
Btw, it seems that the v1.0.2 tag hasn't been pushed to the repo.

**Comment by mlewand** [comment]
Thanks for noting that, definitely I'll try to give it some love this evening or tomorrow at latest.

**Comment by fredck** [comment]
As for me, no time pressure. I'll get back to this next week only.

Thanks again!

**Comment by mlewand** [comment]
Should be working fine now :ok\_hand:

**Comment by fredck** [comment]
It's perfect: ckeditor/github-writer@6240f7e. Thanks!
